#!/usr/bin/env python3

import json
import sys

from jinja2 import Environment, FileSystemLoader

from seoanalyzer import analyze

if __name__ == "__main__":
    site = ''
    sitemap = ''
    output_type = 'json'

    if len(sys.argv) == 2:
        site = sys.argv[1]
        sitemap = None
    elif len(sys.argv) == 3:
        site = sys.argv[1]
        sitemap = site + sys.argv[2]
    elif len(sys.argv) == 4:
        site = sys.argv[1]
        sitemap = site + sys.argv[2]
        output_type = sys.argv[3]
    else:
        print("Usage: seoanalyzer http://www.site.tld [sitemap] [html|json]")
        exit()

    output = analyze(site, sitemap)

    if output_type == 'html':
        #template rendering
        #https://stackoverflow.com/questions/11857530/how-do-i-render-jinja2-output-to-a-file-in-python-instead-of-a-browser
        env = Environment(loader=FileSystemLoader('templates'))
        template = env.get_template('index.html')
        output_from_parsed_template = template.render(result=output)
        print(output_from_parsed_template)
    else:
        print(json.dumps(output, indent=4, separators=(',', ': ')))
